### ISSUE TITLE
Unable to click hyperlink on Linux. Getting noSuchElement exception

### ISSUE THREAD

**Issue by Ravi-Prasad** [serenity-bdd/serenity-cucumber#99] opened 2017-10-18 14:35 UTC
We are able to click hyperlink on windows using JS Executor but not able to click hyperlink on Linux. We are using headless browser ie., PhantomJs. We have tried Actions and WebElement Click and JS Executor Click to click the hyperlink but none of the option worked out. Thanks in advance

**Comment by wakaleo** [comment] 2017-10-18 14:38
This sounds like a phantomJS issue. Do you have anything that indicates that the problem is coming from the Serenity code (e.g. it works with raw webdriver but not with a WebElementFacade?

**Comment by Ravi-Prasad** [comment] 2017-10-19 18:00
No, we have tried with raw webdriver alone but not with WebElementFacade .  It was working fine earlier but lately we are getting org.openqa.selenium.NoSuchElementException: Timed out after 2 seconds. Element not found error message. As I said earlier it is working fine in my local and on Jenkins Slave machine(Windows). But getting error when we hit the pipeline runs on Linux.
We are using below JS to click the element -
JavascriptExecutor executor = (JavascriptExecutor) consolePage.getDriver();		 executor.executeScript("arguments[0].click();", element);

**Comment by wakaleo** [comment] 2017-10-19 18:08
This sounds like an environment-specific issue, possibly a PhantomJS bug. If it works locally it is unlikely to be a WebDriver issue. Have you considered using chrome in headless mode, or xvfs on the Linux environment (phantom hs is not always 100% reliable)

**Comment by Ravi-Prasad** [comment] 2017-10-19 18:22
haven't tried with chrome headless mode. 
Not sure how to use xvfs on the Linux environment. Thanks

**Comment by wakaleo** [comment] 2017-11-02 09:28
Closing as unrelated to serenity-cucumber.

**Closed by wakaleo** 2017-11-02 09:28 UTC
