### ISSUE TITLE
Scenario Outline with PendingException marked as Passing instead of Pending

### ISSUE THREAD

**Issue by dwursteisen** [serenity-bdd/serenity-cucumber#21] opened 2015-12-04 10:06 UTC
Hello, 

If a scenario outline has steps which throwing `PendingException`, the scenario is marked as *Passing*.
I expected this scenario should be marked as *Pending*. Is it expected ?

If the scenario is not a scenario outline, the scenario is marked as *Ignored* 
It's not *Pending*, as I would expeded but, unlike the previous result, it's not a false positive.

**To reproduce the problem :** 
- clone the repository https://github.com/dwursteisen/serenity-bug-report and do a `mvn clean install`
- check serenity result with the file `target/site/serenity/index.html`
- the test is marked as *Passing*

I think that the problem is in the `SerenityReporter` which doesn't support *Pending* result.
In the previous repository, I try to fix the problem building my own `SerenityReporter` : Please see `CucumberWithSerenityFix` class

**Comment by cliviu** [comment] 2015-12-14 11:26
Hi @dwursteisen . Thanks for the efforts of creating the bug report.  Your change looks good, I will analyse it and I will get back to you.

**Comment by cliviu** [comment] 2015-12-19 23:53
Hi  @dwursteisen. I reviewed your bug fix and integrated in serenity cucumber, now the report looks like this for the scenario outline : 
![all_examples](https://cloud.githubusercontent.com/assets/2623175/11915703/ad3fdccc-a6b3-11e5-8858-162fdfd69b85.png)

![all_examples_steps](https://cloud.githubusercontent.com/assets/2623175/11915704/ad4474da-a6b3-11e5-9a89-261ce737f434.png)

After one step throws the PendingException, all following steps are marked as Skipped/Ignored.

**Comment by YamStranger** [comment] 2016-01-06 08:40
It seems that this bug already fixed and can not be reproduced

**Closed by YamStranger** 2016-01-06 08:40 UTC
Labels: bug
