### ISSUE TITLE
Error Cucumber (java.time.DateTimeException: Field DayOfYear cannot be printed as the value 100 exceeds the maximum print width of 2)

### ISSUE THREAD

**Issue by Hendrione** [serenity-bdd/serenity-cucumber#141] opened 2018-04-10 06:44 UTC
Getting error today when running serenity cucumber with latest version 1.9.4. Today (10th april 2018) actually day 100 for this year. Here is my log:

```
java.time.DateTimeException: Field DayOfYear cannot be printed as the value 100 exceeds the maximum print width of 2

	at java.time.format.DateTimeFormatterBuilder$NumberPrinterParser.format(DateTimeFormatterBuilder.java:2548)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.lambda$buildTestSuiteElement$0(JUnitXMLConverter.java:197)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.buildTestSuiteElement(JUnitXMLConverter.java:196)
	at net.thucydides.core.reports.junit.JUnitXMLConverter.write(JUnitXMLConverter.java:36)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.lambda$generateReportsFor$0(JUnitXMLOutcomeReporter.java:49)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1683)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
	at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:160)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:583)
	at net.thucydides.core.reports.junit.JUnitXMLOutcomeReporter.generateReportsFor(JUnitXMLOutcomeReporter.java:41)
	at net.thucydides.core.reports.ReportService.generateJUnitTestResults(ReportService.java:202)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:187)
	at net.thucydides.core.reports.ReportService.generateReportsFor(ReportService.java:135)
	at cucumber.runtime.formatter.SerenityReporter.generateReports(SerenityReporter.java:857)
	at cucumber.runtime.formatter.SerenityReporter.handleTestRunFinished(SerenityReporter.java:298)
	at cucumber.runtime.formatter.SerenityReporter.lambda$new$6(SerenityReporter.java:117)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:128)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

**Comment by GJKrupa** [comment] 2018-04-10 08:08
Also getting this issue.  Last good version appears to be 1.6.13.

**Comment by Hendrione** [comment] 2018-04-10 09:15
Yes.. when use **mvn clean verify**, the report will be broken also

**Comment by wakaleo** [comment] 2018-04-10 12:17
Duplicate of https://github.com/serenity-bdd/serenity-core/issues/1195

**Closed by wakaleo** 2018-04-10 12:17 UTC
