### ISSUE TITLE
@manual annotation does not work for scenario outlines

### ISSUE THREAD

**Issue by GeeChao** [serenity-bdd/serenity-cucumber#58] opened 2016-05-19 07:47 UTC
Hi im using serenity-core 1.1.31 and tagging a scenario outline with @manual does not work properly

It works only for the first example then the following ones actually run all the remaining examples even though it's been tagged at the scenario outline level.

**Comment by YamStranger** [comment] 2016-06-03 16:46
Hello @GeeChao Please add short example.

Thanks!!

**Comment by Moustakas42** [comment] 2016-06-09 13:43
Doesn't work for me either. This is what happens:

1. Scenario runs as if it weren't marked with @manual 
2. Scenario passes and is marked as PENDING
3. Maven hangs at aggregate, report never finishes

(I don't know how much of this is expected behavior, hopefully not much. Some more comprehensive documentation would be welcome though.)

**Comment by Moustakas42** [comment] 2016-06-10 09:27
Scenario Outlines tagged with @manual run as if they weren't tagged.

Scenarios tagged with @manual are skipped and reported as Pending (manual).

But is there any way to mark them as PASSED?

**Comment by wakaleo** [comment] 2016-06-10 09:38
This is currently the intended behaviour for the normal manual tests - the @manual tag is just a reminder that a feature needs manual testing, as there is no way you can reliably guarantee that a feature has really been manually tested for a particular build from within the source code.

**Comment by wakaleo** [comment] 2016-06-10 09:40
Maybe you could describe how you intend to use the manual tag?

**Comment by GeeChao** [comment] 2016-06-10 09:41
Hi @YamStranger 

All I do is tag a scenario outline with @manual and it behaves that way

.e.g
Scenario Outline: example
Given I'm on the wikipedia page
When I search for <search term>
Then I'm at the <search term> wiki page
Examples:
| search term |
| homer simpson |
| mcdonalds |
| lexus |

It will not run the first scenario, but it will be tagged as manual on the report and each step will be skipped.
HOWEVER, for mcdonalds and lexus, it will actually run the methods if they ARE implemented in Cucumber.

**Comment by wakaleo** [comment] 2016-06-10 10:11
Could you try with 1.1.37-rc.3?

**Comment by Moustakas42** [comment] 2016-06-10 10:18
@wakaleo is there any way to mark tests as PASSED for reporting? Cucumber has Hooks that can be combined with tags, maybe the Serenity runner can force them to pass somehow?

**Comment by cliviu** [comment] 2016-06-13 21:16
hi @GeeChao. 
I have  run the test with serenity-core 1.1.31 and serenity-cucumber1.1.6 and I was able to reproduce your original problem.  
I have tested with serenity core 1.1.36 and  serenity-cucumber-1.1.9 and the problem cannot be reproduced anymore.  Please try for yourself with the above library combination and give us your valuable feedback. Thanks !

**Comment by GeeChao** [comment] 2016-06-14 05:06
Awesome, thanks @cliviu, much appreciated

**Comment by aquadrehz** [comment] 2016-06-29 08:44
I've try on @cliviu advise and it passed correctly.

![serenity-cucumber-58 manualannotationpassed](https://cloud.githubusercontent.com/assets/3850078/16446121/36e86a68-3e10-11e6-9481-02cdf16a24a2.png)

**Comment by YamStranger** [comment] 2016-06-29 15:42
@GeeChao thanks for this issue!!

It seems that this issue is solved, so I close this ticket.

**Closed by YamStranger** 2016-06-29 15:42 UTC
Labels: bug
